language: r
sudo: false
r: 3.6.1

# Install packrat if needed and have it restore packages.
install:
  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
  - R -e "packrat::packify(); packrat::restore()"

cache:
  # Main R library
  packages: true
  directories:
    # Packrat packages
    - packrat/lib

    
addons: # get google-chrome-stable
  chrome: stable
  
  
before_install:
  - # start your web application and listen on `localhost`
  - "/Applications/Google\\ Chrome.app/Contents/MacOS/Google\\ Chrome --headless --disable-gpu --remote-debugging-port=9222 http://localhost &"
  
  
install: # Install ChromeDriver (64bits; replace 64 with 32 for 32bits).
  - wget -N http://chromedriver.storage.googleapis.com/2.30/chromedriver_linux64.zip -P ~/
  - unzip ~/chromedriver_linux64.zip -d ~/
  - rm ~/chromedriver_linux64.zip
  - sudo mv -f ~/chromedriver /usr/local/share/
  - sudo chmod +x /usr/local/share/chromedriver
  - sudo ln -s /usr/local/share/chromedriver /usr/local/bin/chromedriver
    
    
script:
  - whereis google-chrome-stable
  - google-chrome-stable --version
  - whereis chromedriver
  - R -f run_tests.R



#old
#language: r
#sudo: false
#r: 3.6.1

# Install packrat if needed and have it restore packages.
#install:
#  - R -e 'if (system.file(package="packrat") == "") install.packages("packrat")'
#  - R -e "packrat::packify(); packrat::restore()"

#cache:
  # Main R library
#  packages: true
#  directories:
    # Packrat packages
#    - packrat/lib
    # PhantomJS
#    - travis_phantomjs


# Install PhantomJS (if not cached)
#before_install:
#  - "export PHANTOMJS_VERSION=2.1.1"
#  - "phantomjs --version"
#  - "export PATH=$PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64/bin:$PATH"
#  - "hash -r"
#  - "phantomjs --version"
#  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then rm -rf $PWD/travis_phantomjs; mkdir -p $PWD/travis_phantomjs; fi"
#  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then wget https://github.com/Medium/phantomjs/releases/download/v$PHANTOMJS_VERSION/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -O $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2; fi"
#  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then tar -xvf $PWD/travis_phantomjs/phantomjs-$PHANTOMJS_VERSION-linux-x86_64.tar.bz2 -C $PWD/travis_phantomjs; fi"
#  - "if [ $(phantomjs --version) != $PHANTOMJS_VERSION ]; then hash -r; fi"
#  - "phantomjs --version"

#script:
#  - R -f run_tests.R
